
# TRA04: ¿Qué equipos monitorizan cada tramo?

PREFIX edinttraf: <https://edint.es/def/trafico#>

SELECT ?equipment ?section
WHERE {
  ?equipment a edinttraf:TrafficEquipment ;
             edinttraf:monitors ?section .
}