
# TRA02: ¿Qué incidencias son planificadas y cuáles no?

PREFIX edinttraf: <https://edint.es/def/trafico#>

SELECT ?incidence ?type
WHERE {
  {
    ?incidence a edinttraf:PlannedIncidence .
    BIND("Planned" AS ?type)
  }
  UNION
  {
    ?incidence a edinttraf:UnplannedIncidence .
    BIND("Unplanned" AS ?type)
  }
}

