
# TRA01: ¿En qué tramo ocurre cada incidencia?

PREFIX edinttraf: <https://edint.es/def/trafico#>

SELECT ?incidence ?section
WHERE {
  ?incidence a edinttraf:Incidence ;
             edinttraf:IncidenceInSection ?section .
}
